FROM ubuntu AS dsv-env
CMD ["echo", "imagem de desenvolvimento"]

FROM ubuntu AS hml-env
CMD ["echo", "imagem de homologação"]

FROM ubuntu AS prd-env
CMD ["echo", "imagem de produção"]

FROM ubuntu AS tst-env
CMD ["echo", "imagem de teste"]